apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::645094221920:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::865275171644:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Q1GROP9OQKRM
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-29T19:22:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1162"
  uid: 93663562-860a-4207-bcdf-2ee09d95cc41
